/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab3;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author jason
 */
public class VocabView extends javax.swing.JFrame {

    /**
     * Creates new form VocabView
     */
    //Link to the controller
    public VocabView() {
        initComponents();
    }
    
        private VocabController controller;
    private Scanner scanner = new Scanner(System.in);

    public void setController(VocabController c) {
        this.controller = c;
    }

    public void doAdd() {
        String vocab = entryTF.getText();    
        String meaning = meaningTF.getText();
        String wordClass = wordClassTF.getText();
        if(!vocab.isEmpty()){
            if(!meaning.isEmpty()){
                if(!wordClass.isEmpty()){
                    controller.addToModel(vocab, meaning, wordClass);
                    showMessage("New entry added.");                   
                }else{
                    showMessage("Please input the (Word Class:) text field");
                }
            }else{
                showMessage("Please input the (Meaning:) text field");
            }
        }else{
            showMessage("Please input the (Entry:) text field");
        }
    }

    public void doDelete(String vocab) {
        controller.deleteFromModel(vocab);
        showMessage(vocab +" is deleted.");
    }

    public void doLookup(String vocab) {
        try{
        controller.lookupFromModel(vocab);            
        }catch(NullPointerException err){
            showMessage(vocab + " cannot be found!");            
        }
    }

    public void showMessage(String s) {
        JOptionPane.showMessageDialog(this, s);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VocabTitlePan = new javax.swing.JPanel();
        TitleTF = new javax.swing.JLabel();
        InputPan = new javax.swing.JPanel();
        entryLabel = new javax.swing.JLabel();
        meaningLabel = new javax.swing.JLabel();
        wordClassLabel = new javax.swing.JLabel();
        entryTF = new javax.swing.JTextField();
        meaningTF = new javax.swing.JTextField();
        wordClassTF = new javax.swing.JTextField();
        LookupBT = new javax.swing.JButton();
        DeleteBT = new javax.swing.JButton();
        AddBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VocabTitlePan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TitleTF.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TitleTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleTF.setText("Vocab 3.1");

        javax.swing.GroupLayout VocabTitlePanLayout = new javax.swing.GroupLayout(VocabTitlePan);
        VocabTitlePan.setLayout(VocabTitlePanLayout);
        VocabTitlePanLayout.setHorizontalGroup(
            VocabTitlePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VocabTitlePanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VocabTitlePanLayout.setVerticalGroup(
            VocabTitlePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VocabTitlePanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TitleTF)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        InputPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entryLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entryLabel.setText("Entry:");

        meaningLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        meaningLabel.setText("Meaning:");

        wordClassLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wordClassLabel.setText("Word Class:");

        javax.swing.GroupLayout InputPanLayout = new javax.swing.GroupLayout(InputPan);
        InputPan.setLayout(InputPanLayout);
        InputPanLayout.setHorizontalGroup(
            InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meaningLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordClassLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meaningTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordClassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        InputPanLayout.setVerticalGroup(
            InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meaningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meaningTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordClassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        LookupBT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LookupBT.setText("Lookup");
        LookupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookupBTActionPerformed(evt);
            }
        });

        DeleteBT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DeleteBT.setText("Delete");
        DeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTActionPerformed(evt);
            }
        });

        AddBT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddBT.setText("Add");
        AddBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VocabTitlePan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LookupBT)
                        .addGap(75, 75, 75)
                        .addComponent(AddBT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VocabTitlePan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LookupBT)
                    .addComponent(DeleteBT)
                    .addComponent(AddBT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LookupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookupBTActionPerformed
        // TODO add your handling code here:
        String vocab = entryTF.getText();
        doLookup(vocab);
    }//GEN-LAST:event_LookupBTActionPerformed

    private void AddBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTActionPerformed
        // TODO add your handling code here:
        doAdd();
    }//GEN-LAST:event_AddBTActionPerformed

    private void DeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTActionPerformed
        // TODO add your handling code here:
        String vocab = entryTF.getText();
        doDelete(vocab);
    }//GEN-LAST:event_DeleteBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VocabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VocabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VocabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VocabView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VocabView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBT;
    private javax.swing.JButton DeleteBT;
    private javax.swing.JPanel InputPan;
    private javax.swing.JButton LookupBT;
    private javax.swing.JLabel TitleTF;
    private javax.swing.JPanel VocabTitlePan;
    private javax.swing.JLabel entryLabel;
    private javax.swing.JTextField entryTF;
    private javax.swing.JLabel meaningLabel;
    private javax.swing.JTextField meaningTF;
    private javax.swing.JLabel wordClassLabel;
    private javax.swing.JTextField wordClassTF;
    // End of variables declaration//GEN-END:variables
}
